package com.hekabe.dashboard.shared.parameter;

public interface StringParameter {
	public static final String AMAZON_EC2 = "Amazon EC2";
	public static final String ONE_AND_ONE_CLOUD = "1&1 Cloud";
	public static final String MANAGEMENT = "Management";
	public static final String NEW_CLUSTER = "New Cluster";
	public static final String FIRST_HARDWARE = "1. Hardware";
	public static final String SECOND_CASSANDRA = "2. Cassandra";
	public static final String THIRD_CASSANDRA_CONFIG_TUNING = "3. Cassandra Config Tuning";
	public static final String PROVIDER = "Provider";
	public static final String ACCESS_KEY = "Access Key";
	public static final String SECRET_ACCESS_KEY = "Secret Access Key";
	public static final String IPS = "IPs";
	public static final String LOGIN = "Login";
	public static final String ROOT ="root";
	public static final String PASSWORD = "Password";
	public static final String CLUSTER = "Cluster";
	public static final String NUMBER_OF_INSTANCES = "Number of instances";
	public static final String REGION = "Region";
	public static final String US_EAST_VIRGINIA = "US East (Virginia)";
	public static final String US_WEST_OREGON = "US West (Oregon)";
	public static final String US_WEST_CALIFORNIA =  "US West (California)";
	public static final String EU_WEST_IRELAND = "EU West (Ireland)"; 
	public static final String ASIA_PACIFIC_SINGAPORE = "Asia Pacific (Singapore)";
	public static final String ASIA_PACIFIC_TOKYO = "Asia Pacific (Tokyo)";
	public static final String SOUTH_AMERICA_SAO_PAULO = "South America (Sao Paulo)";
	public static final String LARGE = "Large (m1.large)";
	public static final String EXTRA_LARGE = "Extra Large (m1.xlarge)";
	public static final String HIGH_MEMORY_EXTRA_LARGE = "High-Memory Extra Large (m2.xlarge)";
	public static final String HIGH_MEMORY_DOUBLE_EXTRA_LARGE = "High-Memory Double Extra Large (m2.2xlarge)";
	public static final String HIGH_MEMORY_QUADRUPLE_EXTRA_LARGE = "High-Memory Quadruple Extra Large (m2.4xlarge)";
	public static final String HIGH_CPU_EXTRA_LARGE = "High-CPU Extra Large (c1.xlarge)";
	public static final String ONE_POINT_ZERO = "1.0";
	public static final String RANDOM_PARTITIONER = "Random Partitioner";
	public static final String BYTE_ORDERED_PARTITIONER = "Byte Ordered Partitioner";
	public static final String ENABLED = "Enabled";
	public static final String DISABLED = "Disabled";
	public static final String PERIODIC = "periodic";
	public static final String BATCH = "batch";
	public static final String LOGGED_IN_AS = "Logged in as: ";
	public static final String HEKABE_DASHBOARD = "Hekabe Dashboard";
}
